# Generated by Django 5.1.7 on 2025-04-03 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            (1, "First Period"),
                            (2, "Second Period"),
                            (3, "Third Period"),
                            (4, "Fourth Period"),
                            ("RT", "Raider Time"),
                        ],
                        max_length=2,
                    ),
                ),
                ("room_number", models.CharField(max_length=10)),
                ("capacity", models.IntegerField(default=30)),
                ("current_enrollment", models.IntegerField(default=0)),
                ("subject", models.CharField(max_length=100)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("teacher", "period")},
            },
        ),
    ]
